apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-delete-deployment
  labels:
    app: contact-delete
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-delete
  template:
    metadata:
      labels:
        app: contact-delete
    spec:
      containers:
        - name: contact-delete-container
          image: gugol94/fiapcontacts-delete:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
