# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: contacts-delete-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RabbitMq__Host: "amqps://admin:admin@rabbitmq:5672/"
  RabbitMq__Queue: "contact.delete"

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-delete-deployment
  labels:
    app: contact-delete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-delete
  template:
    metadata:
      labels:
        app: contact-delete
    spec:
      containers:
        - name: contact-delete-container
          image: gugol94/fiapcontacts-delete:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: contacts-delete-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "150m"
